spring.application.name=${SPRING_APP_NAME:spring-boot-4-usermanagement}

spring.jpa.hibernate.ddl-auto=update

# security
spring.security.user.name=admin
spring.security.user.password=12345

# logging
logging.pattern.console=${LOGPATTERN_CONSOLE:%clr(%d{HH:mm:ss.SSS}){green} %clr(%-5level){blue} %clr([%thread]){red} %clr(%logger{15}){yellow} - %msg%n}
logging.level.org.springframework.security=${SPRING_SECURIY_LOG_LEVEL:TRACE}